 synthetic-package: false

 arb-dir: lib/l10n
 template-arb-file: app_es.arb
 output-dir: lib/src/core/localization
 output-localization-file: app_localizations.dart
 untranslated-messages-file: untranslated_messages.txt
 output-class: AppLocalizations